import {Poppins, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const rubikFont = Rubik({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const headingsFont = Poppins({
  variable: "--font-headings",
  subsets: ["latin"],
  weight: ["600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${headingsFont.variable} ${rubikFont.variable} antialiased`}
      >
        <main className="dark:bg-gray-800 bg-white dark:text-white text-black min-h-screen">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
